---
title: "Events at Rome R Users Group"
subtitle: "Join us for engaging events focused on R programming and data science."
description: "**Discover our upcoming and past events designed to foster learning, collaboration, and community building around R programming in Rome.**"
listing:
  contents: posts
  sort: "date desc"
  type: grid
  image-height: "400"
  categories: true
page-layout: full
title-block-banner: false
sidebar: true
---


Events are the heartbeat of our community. They bring us together to learn, collaborate, and connect. Whether it’s a workshop, a meetup, or a project showcase, each event is an opportunity to share knowledge, build skills, and grow the R programming community in Rome and beyond.

Our in-person focused group events are designed to foster deeper conversations and hands-on collaboration in smaller, interactive settings. Unlike large meetups, these sessions create space for participants to dive into specific topics, exchange ideas, and work through challenges side by side. By bringing people together in the same room, we create a supportive environment where learning feels personal, networking happens naturally, and everyone has a chance to contribute.

## Upcoming Events

> For More Information about Next Events/Workshops/Tutorials Please Check: <https://www.meetup.com/rome-r-users-group/>

:::: {.grid}


::::

## Past Events








