name: Update Feeds
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Render Site
        run: ./render-site.sh
      - name: Check if News Index Exists
        run: test -f ./_site/content/news/index.html
      - name: Deploy
        run: ./deploy.sh
        env:
          PUBLISH_DIR: './_site'